version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Verify.Xunit
    versions:
    - 11.0.0
    - 11.0.1
    - 11.0.2
    - 11.0.3
    - 11.1.0
    - 11.2.0
    - 11.4.0
    - 11.7.0
    - 11.8.0
