<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\MethodDecorator.Fody.Tests\AssemblyExtensions.cs" Link="AssemblyExtensions.cs" />
    <Compile Include="..\MethodDecorator.Fody.Tests\Method.cs" Link="Method.cs" />
    <Compile Include="..\MethodDecorator.Fody.Tests\StaticMembersDynamicWrapper.cs" Link="StaticMembersDynamicWrapper.cs" />
    <Compile Include="..\MethodDecorator.Fody.Tests\TestsBase.cs" Link="TestsBase.cs" />
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <ProjectReference Include="..\MethodDecorator.Fody\MethodDecorator.Fody.csproj" />
    <ProjectReference Include="..\MethodDecorator\MethodDecorator.csproj" />
    <ProjectReference Include="..\TestAssemblies\AnotherAssemblyAttributeContainer\AnotherAssemblyAttributeContainer.csproj" />
    <ProjectReference Include="..\TestAssemblies\SimpleTest.PnP\SimpleTest.PnP.csproj" />
  </ItemGroup>
</Project>