name: on-push-run-build
on:
  push:
  
env:
  # Opt out of telemetry
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build_linux:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    - name: Build with dotnet
      run: dotnet build --configuration Debug
      
    - name: Run unit tests
      run: dotnet test --no-build -c Debug

  build_windows:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    - name: Build with dotnet
      run: dotnet build --configuration Debug
      
    - name: Run unit tests
      run: dotnet test --no-build -c Debug
